version: "3.9"
services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: res
      POSTGRES_USER: res
      POSTGRES_DB: restaurant
    ports:
      - "5434:5432"